In [2]:
# Import libraries
import pandas as pd
import numpy as np
from numpy import genfromtxt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data=genfromtxt('/content/drive/MyDrive/bank_note_data.txt',delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [ ]:
labels=data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
features=data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

x=features
y=labels

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=0.2,random_state=0)

In [ ]:
x_train

array([[-1.2943  ,  2.6735  , -0.84085 , -2.0323  ],
       [-0.40857 ,  3.0977  , -2.9607  , -2.6892  ],
       [-1.5228  , -6.4789  ,  5.7568  ,  0.87325 ],
       ...,
       [ 0.6005  ,  0.99945 , -2.2126  ,  0.097399],
       [ 2.0165  , -0.25246 ,  5.1707  ,  1.0763  ],
       [-2.0759  , 10.8223  ,  2.6439  , -4.837   ]])

In [ ]:
x_test

array([[ -1.7713  , -10.7665  ,  10.2184  ,  -1.0043  ],
       [  5.1321  ,  -0.031048,   0.32616 ,   1.1151  ],
       [ -2.0149  ,   3.6874  ,  -1.9385  ,  -3.8918  ],
       ...,
       [ -2.1652  ,   3.0211  ,  -2.4132  ,  -2.4241  ],
       [  0.48797 ,   3.5674  ,  -4.3882  ,  -3.8116  ],
       [ -4.3667  ,   6.0692  ,   0.57208 ,  -5.4668  ]])

In [ ]:
y_train

array([1., 1., 1., ..., 1., 0., 0.])

#Standardize the datset

In [ ]:

#scaling

from sklearn.preprocessing import MinMaxScaler

scaler_object=MinMaxScaler()

scaler_object.fit(x_train)

scaled_x_train=scaler_object.transform(x_train)

scaled_x_test=scaler_object.transform(x_test)

scaled_x_test


array([[0.38009937, 0.11250267, 0.66790876, 0.66254348],
       [0.87793234, 0.51420791, 0.24176708, 0.86962129],
       [0.36253236, 0.6533469 , 0.14420919, 0.38041779],
       ...,
       [0.3516936 , 0.62841491, 0.12375988, 0.52382069],
       [0.54302476, 0.64885668, 0.03868008, 0.3882538 ],
       [0.19293425, 0.74247045, 0.25236091, 0.22653105]])

In [ ]:
scaled_x_train.max()

1.0

In [ ]:
scaled_x_train.min()

0.0

In [ ]:
scaled_x_test.max()

0.987767870172537

In [ ]:
scaled_x_test.max()

0.987767870172537

#Building neural network

In [ ]:
pip install keras #keras==tensorflow

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
#creating model in a sequence
model=Sequential()

#neurons 5--hidden layer 1
model.add(Dense(4,input_dim=4,activation='relu'))

#neurons 2--hidden layer 1
model.add(Dense(2,activation='relu'))

#neurons 1--Output layer 1
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#Compile  MODEL

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#Training the model


In [1]:
model.fit(scaled_x_train,y_train,epochs=250,verbose=1)

#divides the data into 35 chunks,pure data set ko chunks mai
#kar ke w aur b ki values ko sahi karta
#thora thora data de kar loss check karrta take bar bar pura data na dena parhe
#step by step epoch on chunks

# 1 epochs == jab model pure data aik bar dekhta learn karta
# 35 chunks ko check karta aik epochs

NameError: name 'model' is not defined

#Prediction on unseen **Values**

In [ ]:
predictions=model.predict(scaled_x_test)
predictions
#this is giving  probablities of being 1.

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[9.97497380e-01],
       [1.88771992e-05],
       [9.99537408e-01],
       [5.07917593e-06],
       [4.46734748e-06],
       [3.60531594e-05],
       [8.65734933e-07],
       [2.59626049e-05],
       [9.91440952e-01],
       [9.96907711e-01],
       [1.54032132e-05],
       [6.07248467e-07],
       [9.99611437e-01],
       [3.95561216e-07],
       [8.89928469e-06],
       [4.71760222e-06],
       [9.99986410e-01],
       [9.98166084e-01],
       [8.96273741e-06],
       [8.74009311e-06],
       [9.82113302e-01],
       [2.14965758e-03],
       [8.78428580e-07],
       [9.97101545e-01],
       [9.01819840e-02],
       [9.95777428e-01],
       [6.19015600e-06],
       [9.99113142e-01],
       [1.91457756e-03],
       [3.57794561e-05],
       [9.93565202e-01],
       [8.13884065e-02],
       [9.65930760e-01],
       [9.99930561e-01],
       [9.99920666e-01],
       [1.73603603e-05],
       [1.73206881e-05],
       [9.99210477e-01],
       [2.08645986e-04],
       [9.99239326e-01],


#Proper results

In [ ]:
predicted_classes=np.where(predictions>0.5,1,0)
predicted_classes

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
    

#Evaluating the model performance

In [ ]:
model.metrics_names

['loss', 'compile_metrics']

In [ ]:
model.evaluate(x=scaled_x_test,y=y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9904 - loss: 0.0211 


[0.020778842270374298, 0.9927272796630859]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(classification_report(y_test,predicted_classes))

print(confusion_matrix(y_test,predicted_classes))

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99       157
         1.0       0.98      1.00      0.99       118

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

[[155   2]
 [  0 118]]


In [ ]:
model.save('myfirstmodel.h5')

#.h5 == format

In [ ]:
from keras.models import load_model

In [ ]:
loaded_model = load_model('myfirstmodel.h5')