##### Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for performing complex mathematical operations. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

1. Initializing the NumPy arrays
2. Accessing elements
3. Array types
4. Array Dimensions and Shapes
5. Indexing and Slicing of Matrices
6. Statistics functions
7. Broadcasting and Vectorized operations
8. Useful Numpy functions

## MEAN


In [2]:
# mean of a list
a=[2,3,4]
sum=0
for x in a:
  sum=sum+x

average= sum/len(a)
average

3.0

## Standard Deviation

In [1]:
#standard devaition
import math

def calculate_std_deviation(data):
    import math
    # Step 1: Calculate the mean
    mean = sum(data) / len(data)

    # Step 2: Subtract the mean and square the differences
    squared_diffs = [(x - mean) ** 2 for x in data]

    # Step 3: Calculate the mean of the squared differences (variance)
    variance = sum(squared_diffs) / len(data)

    # Step 4: Take the square root of the variance (standard deviation)
    std_deviation = math.sqrt(variance)

    return std_deviation

# Example usage
data = [10, 12, 23, 23, 16, 23, 21, 16]
std_dev = calculate_std_deviation(data)
print(f"Standard Deviation: {std_dev}")


Standard Deviation: 4.898979485566356


### IMPORTING NUMPY

In [ ]:
import numpy as np  # import the library

### BASIC numpy ARRAYS

In [4]:
import numpy as np  # import the library
# Basic Numpy Arrays
a=np.array([1, 2, 3, 4])
a.mean()


2.5

In [ ]:
# In NumPy, when you create an array, it tries to determine a common data type for all the elements.

array1 = np.array([1.67, 7, False])

# NumPy arrays are homogeneous, meaning all elements in an array must have the same data type.

# When you mix types, NumPy automatically promotes all the elements to a common type that can represent all the data without loss. Unicode string with a maximum length of 21 characters.

array1


array([1.67, 7.  , 0.  ])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b = np.array([[9.1,8.1,7.1],[6.0,5.0,4.0],[9.1,8.1,7.1]]) # ([[row1], [row2]])
print(b)

[[9.1 8.1 7.1]
 [6.  5.  4. ]
 [9.1 8.1 7.1]]


In [ ]:
b[0]

array([9.1, 8.1, 7.1])

In [ ]:
# access the individual elements of array a
print(b[1][2])


4.0


In [ ]:
print(b[1,2])

4.0


In [ ]:
#access all elements
print(b[1:,1:])

[[5.  4. ]
 [8.1 7.1]]


## SLICING

In [ ]:
#access from 2nd till 5th element
print(a[1:6]) #slicing

[2 3 4 5 6]


In [ ]:
#negative indexing can be used to access elements from the end
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
a[::-1] # from 1 to -1 [R,C,Step]

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# access the elements step wise [start-index:end-index:step]

a[1::2]

array([ 2,  4,  6,  8, 10])

In [ ]:
# Array Types

b.dtype

dtype('float64')

In [ ]:
b = np.array([20, 25, 19, 1.5, 2]) #array for class age
b.dtype

dtype('float64')

In [ ]:
b = np.array([20, 25, 19, 1.5, 2],dtype=int) #array for class age
print(b)
b.dtype


[20 25 19  1  2]


dtype('int64')

In [ ]:
#change data type

np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [ ]:
b = np.array([[9.1,8.1,7.1],[6.0,5.0,4.0],[9.1,8.1,7.1]])

In [ ]:
# Array Dimensions and shapes

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# A is an array having 2 rows and 3 columns
A.shape

#(2,3) # 2 rows and 3 columns

(2, 3)

In [ ]:
#check the dimensions of array A

A.ndim

2

In [ ]:
#Check the no. of elements in array A
A.size

6

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) # 2 rows 3 columns

B = np.array([
    [
        [12, 11, 10,9],
        [9, 8, 7,88],
    ],
    [
        [6, 5, 4,77],
        [3, 2, 1,66]
    ]
]) # no of matrix= 2 , rows with each= 2 , how many columns qithin each matrxi 3

  # no. of square brackets is going to show the dimention of the arrays

print(B)

[[[12 11 10  9]
  [ 9  8  7 88]]

 [[ 6  5  4 77]
  [ 3  2  1 66]]]


In [ ]:
[
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
  ],
  [
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21],
    [22, 23, 24]
  ]
]
#2 matrix #each mar=trix 4 rows, #each matrix has 3 columns

In [ ]:
B.shape # no. of matrices, no. of rows, no. of cols

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [5]:
#If the shape isn't consistent, it'll give error:

C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
# Indexing and Slicing of Matrices

# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8,9]  # 2
])

In [ ]:
#accessing row 2

A[1]

array([4, 5, 6])

In [ ]:
#accessing elements from row 2
A[1][0]

4

In [ ]:
# [row, col]

A[1, 0]

4

In [ ]:
# accessing rows from 0-2, where 2 is not included

A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# [row start:end, col start:end]

A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# accessing only first 2 rows and 2 col

A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
#accessing last columns of first 2 rows

A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#updating values at position A[1]

A[1] = np.array([10, 10, 10])

In [ ]:
A
# Indexing and Slicing of Matrices

# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8,9]  # 2
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# update the entire row with a scalar value.

A[2] = 99 #row

In [ ]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [ ]:
# Statistics Functions

a = np.array([1, 2, 3, 4]) # 1 row and 4 columns # 1 d with 4 columns

In [ ]:
# add up all values of an array
a.sum()

10

In [ ]:
#calculate mean
B.mean()

6.5

In [ ]:
#calculate standard deviation
a.std()

1.118033988749895

In [ ]:
#calculate variance
a.var()

1.25

In [ ]:
#Example

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.sum()

45

In [ ]:
#col wise addition

A.sum(axis=0)

array([12, 15, 18])

In [ ]:
#row wise addition

A.sum(axis=1) # axis=1 row wise additon

array([ 6, 15, 24])

In [ ]:
#col wise mean

A.mean(axis=0)

# Mean of the first column [1, 4, 7] is (1 + 4 + 7) / 3 = 4.0.
# Mean of the second column [2, 5, 8] is (2 + 5 + 8) / 3 = 5.0.
# Mean of the third column [3, 6, 9] is (3 + 6 + 9) / 3 = 6.0.

array([4., 5., 6.])

In [ ]:
#row wise mean

A.mean(axis=1)

# Mean of the first row [1, 2, 3] is (1 + 2 + 3) / 3 = 2.0.
# Mean of the second row [4, 5, 6] is (4 + 5 + 6) / 3 = 5.0.
# Mean of the third row [7, 8, 9] is (7 + 8 + 9) / 3 = 8.0.

array([2., 5., 8.])

In [ ]:
# Broadcasting and Vectorized operations

# create a NumPy array with sequential integer values ranging from 0 to 3.
a = np.arange(4) #like python range() function

a


array([0, 1, 2, 3])

In [ ]:
#this will add up 10 to all elements of the array

a + 10 # element wise operations

array([10, 11, 12, 13])

In [ ]:
a * 10


array([ 0, 10, 20, 30])

In [ ]:
# array a remains unchanched as the changes are not assigned to it
a

array([0, 1, 2, 3])

In [ ]:
#equal to a = a + 100
a += 100

In [ ]:
#array is now changed
a

array([100, 101, 102, 103])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
a + b

array([110, 111, 112, 113])

In [ ]:
# you can use the + operator to append (or concatenate) two lists in Python

list1 = [1, 2, 3]
list2 = [4, 5, 6]

result = list1 + list2
print(result)

[1, 2, 3, 4, 5, 6]


In [ ]:
a * b

array([1000, 1010, 1020, 1030])

##### Numpy functions

1. random

In [ ]:
A = np.random.random(size=2) 0-0.99999999

# Generates random numbers from a uniform distribution
# between 0 (inclusive) and 1 (exclusive).
# The argument size specifies the shape of the output array.
# size=2 means it will generate an array with two random values.
A

array([0.5832415 , 0.74699502])

In [ ]:
B = np.random.normal(size=2)
# Generates random numbers from a normal (Gaussian) distribution
# with a mean of 0 and a standard deviation of 1 by default.
# The argument size specifies the shape of the output array.
# size=2 means it will generate an array with two random values.
B

array([1.70790842, 2.49460504])

In [ ]:
C = np.random.rand(2, 4)
# Generates random numbers from a uniform distribution between 0 (inclusive) and 1 (exclusive).
# The rand function is typically used to generate random values
# that follow a uniform distribution.
# The argument 2, 4 specifies the shape of the output array.
# 2 rows and 4 columns filled with random values between 0 and 1.
C

array([[0.38200965, 0.41677427, 0.94861073, 0.03478475],
       [0.96185418, 0.05831187, 0.70511718, 0.90322871]])

In [ ]:
# create an array of 3 rows and 3 columns with random values from 0 to 100

A = np.random.randint(100, size=(2, 3, 3))

In [ ]:
A

array([[[12, 36, 18],
        [66, 29, 27],
        [40, 66, 37]],

       [[55, 69, 19],
        [79, 21, 60],
        [ 6, 35, 76]]])

###### 2. arange

In [ ]:
A = np.arange(10)
# Generates a 1-dimensional array with values from 0 up to,
# but not including, 10.
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B = np.arange(5, 10)
# Generate a 1-dimensional array with values starting from 5
# and going up to, but not including, 10.
B

array([5, 6, 7, 8, 9])

In [ ]:
C = np.arange(0, 1, .1)
# Generate a sequence of numbers starting from 0 and incrementing by 0.1
# until it reaches a value just less than 1
C

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

##### 3. reshape

In [ ]:
A = np.arange(9).reshape(3, 3)
# creates a 1-dimensional NumPy array with values from 0 to 9 (inclusive),
# then arranges the values into a 2-dimensional array with 2 rows and 5 columns
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
B = np.arange(10).reshape(5, 2)
# creates a 1-dimensional array with values from 0 to 9 (inclusive),
# then arranges the values into a 2-dimensional array with 5 rows and 2 columns
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##### 4. linspace

In [ ]:
A = np.linspace(0, 1, 5)
# generates 5 evenly spaced values between 0 (inclusive) and 1 (inclusive)
A

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
B = np.linspace(0, 1, 20)
# generates 20 evenly spaced values between 0 (inclusive) and 1 (inclusive).
B

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
C = np.linspace(0, 1, 20, False)
# generates 20 evenly spaced values between 0 (inclusive) and 1,
# but it doesn't include the endpoint (1.0)
C

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

**Reorganizing Arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Vertically stacking

v1 = np.array([[1,2,3,4], [3,3,3,3]])
v2 = np.array([[5,6,7,8], [2,2,2,2]])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [3, 3, 3, 3],
       [5, 6, 7, 8],
       [2, 2, 2, 2]])

In [ ]:
# Horizontal  stack

v1 = np.array([[1,2,3,4], [3,3,3,3]])
v2 = np.array([[5,6,7,8], [2,2,2,2]])

np.hstack((v1,v2))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [3, 3, 3, 3, 2, 2, 2, 2]])

##### 5. zeros, ones, empty

In [ ]:
A = np.zeros(5)
# generates 1D array with five zeros
A

array([0., 0., 0., 0., 0.])

In [ ]:
B = np.zeros((3, 3))
# generates 2D array with 3 rows and 3 columns filled with 0s
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
C = np.ones(5)
# generates 1D array with five ones
C

array([1., 1., 1., 1., 1.])

In [ ]:
D = np.ones((3, 3))
# generates 2D array with 3 rows and 3 columns filled with 1s
D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
E = np.empty(5)
# allocates memory for a 1D array with five elements
# but does not set their values to any specific initial values.
#The values in E will also be uninitialized and may appear as random numbers.
E

array([2.12199579e-314, 4.67296746e-307, 3.71537366e-321, 3.79442416e-321,
       2.33422678e-312])

In [ ]:
F = np.empty((2, 2))
# 2D array with 2 rows and 2 columns without specific initial values.
# The values in F will also be uninitialized and may appear as random numbers.
F

array([[1., 1.],
       [1., 1.]])

##### 6. identity and eye

In [ ]:
A = np.identity(3)
# An identity matrix is a square matrix where all the diagonal elements are 1,
# and all other elements are 0
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
B = np.eye(3, 3)
# creates a 3x3 identity matrix.
#The np.eye() function allows specifying the number of rows and columns
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
C = np.eye(8, 4)
# creating a non-square identity matrix,
# 8x4 matrix where the diagonal elements are 1, and all other elements are 0.
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
D = np.eye(8, 4, k=1)
# creates an 8x4 identity matrix with an offset of 1,
# meaning that the 1's start one position to the right of the main diagonal.
D

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
E = np.eye(8, 4, k=-3)
# creates an 8x4 identity matrix with an offset of -3,
# meaning that the 1's start three positions to the left of the main diagonal.
E

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])